# Generated by Django 4.1.1 on 2022-09-26 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oauth2_login_client", "0002_auto_20190506_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteuser",
            name="user",
            field=models.OneToOneField(
                help_text="Django user",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
